### ISSUE TITLE
Run in release mode, compile error report `Undefined symbol: _rust_greeting`

### ISSUE THREAD

**Issue by Aaron009** [brickpop/flutter-rust-ffi#22] opened 2021-02-04 05:42 UTC
https://github.com/dart-lang/ffi/issues/75

**Comment by brickpop** [comment] 2021-02-04 21:39
There are two points here.

### First
> NOTE: By default, XCode will skip bundling the libexample.a library if it detects that it is not being used. To force its inclusion, add dummy invocations in SwiftMylibPlugin.swift that use every single native function that you use from Flutter:

The workaround on the Readme will get you around the fact that XCode strips unused symbols (from the Swift perspective, ignoring Dart invications).

### Second
Even this trick will not suffice with the latest version of XCode, so there is another issue to track this:
https://github.com/brickpop/flutter-rust-ffi/issues/16#issuecomment-751463556

Closing as duplicate of #16

**Closed by brickpop** 2021-02-04 21:39 UTC
